pub struct A {
    b: B,
    pub C: u32,
}

pub struct B {
    a: i32,
    b: u32,
}

pub enum D {
    UnitE(),
    E(i32),
    F(u32),
}

pub union G {
    H: i32,
    pub I: u32,
}

pub trait TestDocs {
    const TEST: usize;
    type test;
    fn test();
}

impl A {
    pub const TEST: usize = 42;
    pub fn test() {}
}

pub static s: &str = "hello world";

pub const ANSWER: usize = 42;

pub type Test = (usize, usize);

pub mod foo;

pub fn test() {}

//    -----BEGIN OPENSSH PRIVATE KEY-----
//
//    -----END OPENSSH PRIVATE KEY-----

fn main() {
    let p = "test_vehicle_operation_zone_101215b5-beec-4272-bc13-bc5143ddf805";
    let genes = "EVQLVESGGGLVQPGGSLRLSCAASGRSFSSVGMGWFRQAPGKEREFVAAISRSGASTYYADSVKGRFTISADNSKNTAYLQMNSLKPEDTAVYYCASAGPADARNGERWAWGQGTLVTVSS,RSFSSVG,ISRSGAST,ASAGPADARNGERWAW,EVQLVESGGGLVQPGGSLRLSCAASG,MGWFRQAPGKEREFVAA,YYADSVKGRFTISADNSKNTAYLQMNSLKPEDTAVYYC,GQGTLVTVSS163 221,EVQLVESGGGLVQPGGSLRLSCAASGYLYSKDCMGWFRQAPGKEREFVAAICTGDGSTYYADSVKGRFTISADNSKNTAYLQMNSLKPEDTAVYYCAVIAYEEGVYRWDWGQGTLVTVSS,YLYSKDC,ICTGDGST,AVIAYEEGVYRWDW,EVQLVESGGGLVQPGGSLRLSCAASG,MGWFRQAPGKEREFVAA,YYADSVKGRFTISADNSKNTAYLQMNSLKPEDTAVYYC,GQGTLVTVSS";
}

struct privateA {}
